services:
  app:
    build:
      context: .
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: php_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: php_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: php_app
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
